In [1]:
import numpy as np 
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [2]:
train=pd.read_csv("C:\\Users\\ADMIN\\Desktop\\Data_Science\\Project 1\\drug200.csv")

In [3]:
train.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [4]:
train.shape

(200, 6)

In [5]:
from sklearn import preprocessing
le_sex = preprocessing.LabelEncoder()

In [6]:
#le_sex.fit(['F','M'])
#train[:,1] = le_sex.transform(train[:,1]) 

In [7]:
train['Sex']=le_sex.fit_transform(train['Sex']) 
train['Sex'].unique()



array([0, 1], dtype=int64)

In [8]:
le_bp = preprocessing.LabelEncoder()
train['BP']=le_bp.fit_transform(train['BP']) 


In [9]:
train['BP'].unique()

array([0, 1, 2], dtype=int64)

In [10]:
train['Cholesterol'].unique()

array(['HIGH', 'NORMAL'], dtype=object)

In [11]:
le_bp = preprocessing.LabelEncoder()
train['Cholesterol']=le_bp.fit_transform(train['Cholesterol']) 


In [12]:
train['Cholesterol'].unique()

array([0, 1], dtype=int64)

In [13]:
train['Drug'].unique()

array(['drugY', 'drugC', 'drugX', 'drugA', 'drugB'], dtype=object)

In [14]:
le_bp = preprocessing.LabelEncoder()
train['Drug']=le_bp.fit_transform(train['Drug']) 

In [15]:
train['Drug'].unique()

array([4, 2, 3, 0, 1], dtype=int64)

In [16]:
train.head()

Age  Sex  BP  Cholesterol  Na_to_K  Drug
0   23    0   0            0   25.355     4
1   47    1   1            0   13.093     2
2   47    1   1            0   10.114     2
3   28    0   2            0    7.798     3
4   61    0   1            0   18.043     4

In [17]:
train.columns

Index(['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K', 'Drug'], dtype='object')

In [18]:
X=train[['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']]
y=train[['Drug']]

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [21]:
drugTree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
drugTree # it shows the default parameters

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [22]:
drugTree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [23]:
predictions= drugTree.predict(X_test)

In [24]:
predictions[0:5]

array([3, 4, 1, 4, 0])

In [25]:
y_test[0:5]

Drug
37      3
109     4
31      1
89      4
66      0

In [26]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_test, predictions))

DecisionTrees's Accuracy:  0.975


In [27]:
from sklearn.metrics import classification_report,confusion_matrix

In [28]:
print(confusion_matrix(y_test,predictions))

[[ 3  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0  9  1]
 [ 0  0  0  0 18]]


In [29]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         4
           2       1.00      1.00      1.00         5
           3       1.00      0.90      0.95        10
           4       0.95      1.00      0.97        18

   micro avg       0.97      0.97      0.97        40
   macro avg       0.99      0.98      0.98        40
weighted avg       0.98      0.97      0.97        40



In [31]:
drugTree.predict([[25,1,1,0,15]])

array([4])

In [32]:
# RESULT: Means Doctor should provide drug Y to its patients.